"""add_unit_price_to_po_and_purchase_invoices_table

Revision ID: 2fab356a3a47
Revises: a2c7ff268eb5
Create Date: 2026-04-22 09:16:42.692328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fab356a3a47'
down_revision: Union[str, Sequence[str], None] = 'a2c7ff268eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('unit_price', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'unit_price')
    # ### end Alembic commands ###
