"""add config list items and app settings tables

Revision ID: 3f16c66f636b
Revises: 62b1eb478254
Create Date: 2026-08-03 18:21:38.235886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f16c66f636b'
down_revision: Union[str, Sequence[str], None] = '62b1eb478254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('default_payment_terms', sa.String(length=100), nullable=True),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('config_list_items',
    sa.Column('list_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_list_items_id'), 'config_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_config_list_items_list_type'), 'config_list_items', ['list_type'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_config_list_items_list_type'), table_name='config_list_items')
    op.drop_index(op.f('ix_config_list_items_id'), table_name='config_list_items')
    op.drop_table('config_list_items')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
