"""add_quantity_columns_to_purchase_orders

Revision ID: 507726cc506c
Revises: b87c484f9a29
Create Date: 2026-04-22 09:09:22.534145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507726cc506c'
down_revision: Union[str, Sequence[str], None] = 'b87c484f9a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('ordered_quantity', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False))
    op.add_column('purchase_orders', sa.Column('received_quantity', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'received_quantity')
    op.drop_column('purchase_orders', 'ordered_quantity')
    # ### end Alembic commands ###
