"""add selected_supplier_id and awarded status

Revision ID: 84713547c192
Revises: d403f1ce7809
Create Date: 2026-04-08 20:49:43.297781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84713547c192'
down_revision: Union[str, Sequence[str], None] = 'd403f1ce7809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('selected_supplier_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_rfqs_selected_supplier_id'), 'rfqs', ['selected_supplier_id'], unique=False)
    op.create_foreign_key(None, 'rfqs', 'suppliers', ['selected_supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_index(op.f('ix_rfqs_selected_supplier_id'), table_name='rfqs')
    op.drop_column('rfqs', 'selected_supplier_id')
    # ### end Alembic commands ###
