"""initial tables

Revision ID: 86ac587244eb
Revises: 
Create Date: 2026-03-12 06:16:36.070385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ac587244eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_company_name'), 'suppliers', ['company_name'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'PURCHASER', 'FINANCE', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('entity_type', sa.Enum('QUOTATION', 'INVOICE', name='approval_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('delegated_to_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delegated_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_approver_id'), 'approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approvals_delegated_to_id'), 'approvals', ['delegated_to_id'], unique=False)
    op.create_index(op.f('ix_approvals_entity_id'), 'approvals', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approvals_entity_type'), 'approvals', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('entity_type', sa.Enum('RFQ', 'QUOTATION', 'INVOICE', 'SUPPLIER_QUOTE', name='document_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'EXCEL', 'WORD', 'IMAGE', 'OTHER', name='document_type'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_documents_entity_type'), 'documents', ['entity_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_id'), 'documents', ['uploaded_by_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('rfq_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'RECEIVED', 'EVALUATED', 'CLOSED', 'CANCELLED', name='rfq_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_created_by_id'), 'rfqs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_rfqs_id'), 'rfqs', ['id'], unique=False)
    op.create_index(op.f('ix_rfqs_rfq_number'), 'rfqs', ['rfq_number'], unique=True)
    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CONVERTED', name='quotation_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('delivery_terms', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_created_by_id'), 'quotations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_quotations_rfq_id'), 'quotations', ['rfq_id'], unique=False)
    op.create_table('rfq_items',
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('target_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_items_id'), 'rfq_items', ['id'], unique=False)
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    op.create_table('supplier_quotes',
    sa.Column('rfq_item_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('delivery_terms', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'ACCEPTED', 'REJECTED', name='supplier_quote_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_item_id', 'supplier_id', name='uq_supplier_quote_item_supplier')
    )
    op.create_index(op.f('ix_supplier_quotes_id'), 'supplier_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_rfq_item_id'), 'supplier_quotes', ['rfq_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_supplier_id'), 'supplier_quotes', ['supplier_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('rfq_item_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_quote_id', sa.Uuid(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_id'), 'quotation_items', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_items_rfq_item_id'), 'quotation_items', ['rfq_item_id'], unique=False)
    op.create_index(op.f('ix_quotation_items_supplier_quote_id'), 'quotation_items', ['supplier_quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_items_supplier_quote_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_rfq_item_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_supplier_quotes_supplier_id'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_rfq_item_id'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_id'), table_name='supplier_quotes')
    op.drop_table('supplier_quotes')
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_index(op.f('ix_rfq_items_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_quotations_rfq_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_created_by_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_rfqs_rfq_number'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_created_by_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_documents_uploaded_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_entity_type'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_entity_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_delegated_to_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approver_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
