# =============================================================================
# app/models/base.py
# -----------------------------------------------------------------------------
# Reusable SQLAlchemy ORM mixins shared by every model in the application.
# Provides a UUID primary key mixin, an auto-managed timestamp mixin, and a
# combined AuditMixin that all standard models inherit from.
# =============================================================================

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, func
from sqlalchemy.orm import Mapped, mapped_column


def _utcnow() -> datetime:
    """Return the current UTC datetime (timezone-aware).

    Used as a Python-side default for timestamp columns where a server-side
    default is not sufficient (e.g. in-memory objects before flush).

    Returns:
        Current UTC datetime with timezone info.
    """
    return datetime.now(timezone.utc)


# ── Mixins ────────────────────────────────────────────────────────────────────

class UUIDPrimaryKeyMixin:
    """Mixin that adds a UUID ``id`` primary key column to any ORM model.

    The UUID is generated by Python (``uuid.uuid4``) rather than the database
    so that the value is available immediately after object construction,
    before the row is flushed to the database.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )


class TimestampMixin:
    """Mixin that adds server-managed ``created_at`` and ``updated_at`` columns.

    Both columns are populated by the database via ``func.now()``.
    ``updated_at`` is refreshed automatically on every ``UPDATE`` statement
    via ``onupdate``.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),    # refreshed automatically on UPDATE
        nullable=False,
    )


class AuditMixin(UUIDPrimaryKeyMixin, TimestampMixin):
    """Convenience mixin combining UUID primary key and timestamp columns.

    All standard ORM models inherit from this class (along with ``Base``) to
    get ``id``, ``created_at``, and ``updated_at`` without repetition.
    """
    pass
